#-----------------------------------------------------------------------------
#
#  Configuration for continuous integration service at travis-ci.org
#
#-----------------------------------------------------------------------------

language: generic

dist: trusty

#-----------------------------------------------------------------------------

matrix:
  include:

    # Linux Clang Builds

    - os: linux
      compiler: linux-clang38-dev
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['clang-3.8', 'libboost1.55-dev', 'libboost-filesystem1.55-dev', 'libboost-program-options1.55-dev', 'libgdal-dev', 'libproj-dev']
      env: CC='clang-3.8' CXX='clang++-3.8' BUILD_TYPE='Dev'

    - os: linux
      compiler: linux-clang39-dev
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['clang-3.9', 'libboost1.55-dev', 'libboost-filesystem1.55-dev', 'libboost-program-options1.55-dev', 'libgdal-dev', 'libproj-dev']
      env: CC='clang-3.9' CXX='clang++-3.9' BUILD_TYPE='Dev'

    - os: linux
      compiler: linux-clang40-dev
      addons:
        apt:
          sources: ['llvm-toolchain-trusty-4.0', 'ubuntu-toolchain-r-test']
          packages: ['clang-4.0', 'libboost1.55-dev', 'libboost-filesystem1.55-dev', 'libboost-program-options1.55-dev', 'libgdal-dev', 'libproj-dev']
      env: CC='clang-4.0' CXX='clang++-4.0' BUILD_TYPE='Dev'


    - os: linux
      compiler: linux-clang50-release
      addons:
        apt:
          sources: ['llvm-toolchain-trusty-5.0', 'ubuntu-toolchain-r-test']
          packages: ['clang-5.0', 'libboost1.55-dev', 'libboost-filesystem1.55-dev', 'libboost-program-options1.55-dev', 'libgdal-dev', 'libproj-dev']
      env: CC='clang-5.0' CXX='clang++-5.0' BUILD_TYPE='Release'

    - os: linux
      compiler: linux-clang50-dev
      addons:
        apt:
          sources: ['llvm-toolchain-trusty-5.0', 'ubuntu-toolchain-r-test']
          packages: ['clang-5.0', 'libboost1.55-dev', 'libboost-filesystem1.55-dev', 'libboost-program-options1.55-dev', 'libgdal-dev', 'libproj-dev']
      env: CC='clang-5.0' CXX='clang++-5.0' BUILD_TYPE='Dev'


    # Linux GCC Builds

    - os: linux
      compiler: linux-gcc48-dev
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.8', 'libboost1.55-dev', 'libboost-filesystem1.55-dev', 'libboost-program-options1.55-dev', 'libgdal-dev', 'libproj-dev']
      env: CC='gcc-4.8' CXX='g++-4.8' CXXFLAGS='-Wno-return-type' BUILD_TYPE='Dev'

    - os: linux
      compiler: linux-gcc49-dev
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9', 'libboost1.55-dev', 'libboost-filesystem1.55-dev', 'libboost-program-options1.55-dev', 'libgdal-dev', 'libproj-dev']
      env: CC='gcc-4.9' CXX='g++-4.9' BUILD_TYPE='Dev'


    - os: linux
      compiler: linux-gcc5-release
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5', 'libboost1.55-dev', 'libboost-filesystem1.55-dev', 'libboost-program-options1.55-dev', 'libgdal-dev', 'libproj-dev']
      env: CC='gcc-5' CXX='g++-5' BUILD_TYPE='Release'

    - os: linux
      compiler: linux-gcc5-dev
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5', 'libboost1.55-dev', 'libboost-filesystem1.55-dev', 'libboost-program-options1.55-dev', 'libgdal-dev', 'libproj-dev']
      env: CC='gcc-5' CXX='g++-5' BUILD_TYPE='Dev'


    - os: linux
      compiler: linux-gcc6-release
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6', 'libboost1.55-dev', 'libboost-filesystem1.55-dev', 'libboost-program-options1.55-dev', 'libgdal-dev', 'libproj-dev']
      env: CC='gcc-6' CXX='g++-6' BUILD_TYPE='Release'

    - os: linux
      compiler: linux-gcc6-dev
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6', 'libboost1.55-dev', 'libboost-filesystem1.55-dev', 'libboost-program-options1.55-dev', 'libgdal-dev', 'libproj-dev']
      env: CC='gcc-6' CXX='g++-6' BUILD_TYPE='Dev'


    # OSX Clang Builds

    - os: osx
      osx_image: xcode8.3
      compiler: xcode8-clang-dev
      env: CC='clang' CXX='clang++' BUILD_TYPE='Dev'

    - os: osx
      osx_image: xcode9.4
      compiler: xcode9-clang-dev
      env: CC='clang' CXX='clang++' BUILD_TYPE='Dev'

    - os: osx
      osx_image: xcode10.1
      compiler: xcode10-clang-dev
      env: CC='clang' CXX='clang++' BUILD_TYPE='Dev'

    - os: osx
      osx_image: xcode10.1
      compiler: xcode10-clang-release
      env: CC='clang' CXX='clang++' BUILD_TYPE='Release'


#-----------------------------------------------------------------------------

install:
  - git clone --quiet --depth 1 https://github.com/osmcode/libosmium.git ../libosmium
  - git clone --quiet --depth 1 https://github.com/mapbox/protozero.git ../protozero
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      brew install cmake || true
    fi
  - cmake --version

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build && cd build
  - cmake -LA .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE}

script:
  - make VERBOSE=1

#-----------------------------------------------------------------------------
