#-----------------------------------------------------------------------------
#
#  Configuration for continuous integration service at travis-ci.org
#
#-----------------------------------------------------------------------------

language: cpp

sudo: false

matrix:
    include:
        - os: linux
          compiler: clang
          env: BUILD_TYPE=Dev
        - os: linux
          compiler: clang
          env: BUILD_TYPE=Release
        - os: linux
          compiler: gcc
          env: BUILD_TYPE=Dev
        - os: linux
          compiler: gcc
          env: BUILD_TYPE=Release

# http://docs.travis-ci.com/user/apt/
addons:
    apt:
        sources:
            - boost-latest
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
            - gcc-4.8
            - libboost1.55-dev
            - libboost-program-options1.55-dev
            - libgdal-dev
            - libproj-dev

install:
    - git clone --quiet --depth 1 https://github.com/osmcode/libosmium.git ../libosmium

script:
    - mkdir build
    - cd build
    # GCC ignores the pragmas in the code that disable the "return-type" warning selectively, so use this workaround
    - if [ "${CXX}" = 'g++' ]; then
          CXX=g++-4.8;
          CC=gcc-4.8;
          WORKAROUND="-DCMAKE_CXX_FLAGS=-Wno-return-type";
      else
          WORKAROUND="";
      fi
    - echo "travis_fold:start:cmake\nRunning cmake..."
    - cmake -LA -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ${WORKAROUND} ..
    - echo "travis_fold:end:cmake"
    - echo "travis_fold:start:make\nRunning make..."
    - make VERBOSE=1
    - echo "travis_fold:end:make"

